# Вывод логов в stderr для удобства чтения в Docker
logoutput: stdout

# Привязка к интерфейсу (слушаем все адреса внутри контейнера на 1080 порту)
internal: 0.0.0.0 port = 1080

# Исходящий трафик через интерфейс eth0
external: eth0

# Методы аутентификации (в данном случае без пароля, можно изменить на username для авторизации)
socksmethod: username
clientmethod: none

# Настройки привилегий
user.privileged: root
user.notprivileged: nobody

# Разрешаем подключения от любых клиентов к самому прокси
client pass {
    from: 0.0.0.0/0 port 1-65535 to: 0.0.0.0/0
    log: connect disconnect error
}

# Разрешаем проксировать весь трафик (connect, bind, udp) куда угодно
socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    command: bind connect udpassociate
    socksmethod: username
    log: connect disconnect iooperation error

}
